### ISSUE TITLE
AddonStatsApi->getAddonStats()->data->revenue->* uses an incorrect format.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-api-docs#8]
The API returns a formatted USD string:
```json
"current": {
        "day": "$0.00",
        "month": "$0.00"
      },
      "previous": {
        "day": "$0.00",
        "month": "$0.00"
      },
      "total": "$0.00"
```
`data.revenue.current.day -> string`

The OpenAPI schema reports this as an object of
```json
{
    "amount": "string",
    "currency": "string"
}
```

Thus getRevenue()->getCurrent()->getMonth()->getAmount returns null, as the data to populate the model isn't present.

**Comment by TheodoorP** [comment]
Fixed in 55a7d4ae3cf81871c743deb38029f6cfaca24298
